### ISSUE TITLE
[BUG]: Sindre Sorhus link 💀

### ISSUE THREAD

**Issue by Wjplatformer** [2KAbhishek/projects#10]
### Description of the bug

Sindre Sorhus link links to nothing. A possible solution

### Steps To Reproduce

1. Go to `README.md`
2. click on `@sindresorhus` blue link
3. GitHub 404

### Additional Information

![image](https://user-images.githubusercontent.com/82447031/184621278-36da5631-9877-45b7-a0fe-e43290a8b022.png)

![image](https://user-images.githubusercontent.com/82447031/184621091-840dc6ea-06d7-4811-bd00-6972608b70c4.png)

**Comment by 2KAbhishek** [comment]
Thanks for pointing out the error, I've fixed it
