### ISSUE TITLE
[ENH]: New screenshots for markdown

### ISSUE THREAD

**Issue by Wjplatformer** [2KAbhishek/projects#11]
### Description

For the 2.0 update, @2KAbhishek added a `code` and `live` link for certain projects such as GitHub pages and profile README's. I think that changing the `images/screenshot.png` and changing @sindresorhus 's project page would be needed. However, I can't make a PR as my screen is very small and cannot take a big screenshot. :(

### Additional Information

For reference on why it should be changed:
![image](https://user-images.githubusercontent.com/82447031/186425395-9b5e217a-dfae-4798-8b11-82f9e7de616e.png)

**Comment by 2KAbhishek** [comment]
Fixed it, thanks for bringing this up
