### ISSUE TITLE
[BUG]: Incomplete info and text squeeze

### ISSUE THREAD

**Issue by Wjplatformer** [2KAbhishek/projects#12]
### Description of the bug

I had not reviewed my own projects pages in a while, and I found out that not all 17 of my projects are listed on the page. There is also a -1 repo on the repo counter. I tried deleting the fork and forking it again, but it didn't solve the issue. There is also a text squeeze when you search a project. This is a serious bug :skull:

- [x] Incomplete info
- [ ] Text Squeeze

### Steps To Reproduce

1. Go to https://wjplatformer.github.io/projects
2. Count the number of repo's profiles (those square boxes) displayed versus the actual number.
3. See the repo counter and go to https://github.com/Wjplatformer and see the GH repo counter and compare it to the projects counter
4. Search some keywords
5. See the text squeeze

### Additional Information

profile display:
![image](https://user-images.githubusercontent.com/82447031/186655633-26179291-9fa0-46ad-9039-f910a2cfc8be.png)
count display:
![image](https://user-images.githubusercontent.com/82447031/186656312-51d719c8-7d5d-46ca-9edf-7d04bbdfb827.png)
![image](https://user-images.githubusercontent.com/82447031/186656364-ec10254c-8c03-4dcd-8fbb-a0a042239e7f.png)
text squeeze:
![image](https://user-images.githubusercontent.com/82447031/186655677-89847cdd-d872-418c-a6ee-2e3955b41688.png)

**Comment by 2KAbhishek** [comment]
By default forks are hidden in the list, see README to enable it

for the search issue some css tricks are needed, I don't have bandwidth right now, PRs welcome

**Comment by Wjplatformer** [comment]
ok :)

**Comment by Wjplatformer** [comment]
I've already made my fork visible but it still does not solve issue of my project's page incomplete issue. [View it here](https://github.com/Wjplatformer/projects/blob/main/script.js). I will try to do the ccs tricks for the squeezing in the future.

**Comment by 2KAbhishek** [comment]
just set hideForks = false and your forks will be visible

**Comment by Wjplatformer** [comment]
oh. I GUESS the markdown is wrong :raised_eyebrow:. The markdown states that; to SHOW forks, set `hideForks = true` in `script.js`. Obviously, you should set `hideForks = false`. So, if you are like the people who die hard wants to follow instructions, then bad luck for me! In conclusion, `hideForks = true` in the markdown should be changed to `hideForks = false`. (Also, why is that variable set to true in the first place?)

**Comment by 2KAbhishek** [comment]
Ahh, thanks for finding the bug in docs, I've fixed it, also the reason for hiding the forks by default was because I only wanted to show the source repos (since I already have too many of those!)

**Comment by Wjplatformer** [comment]
ohh. that's alright then :)

**Comment by Wjplatformer** [comment]
@2KAbhishek , however, BY default, My `hideForks` was set to `false`! And it still had that problem :|. I guess I have to retry changing it again (like now) and check in a few hours later or smth

**Comment by Wjplatformer** [comment]
Oh! Incomplete info is fixed!

**Comment by Wjplatformer** [comment]
@2KAbhishek , could you send me screenshot of your projects page when you search for a repo? Just checking as I have a different device and text squeeze is resolved. Thanks in advance 😄

**Comment by 2KAbhishek** [comment]
The results are pretty similar to what you have shared, fixing there should provide a general fix

**Comment by Wjplatformer** [comment]
Okie Dokie. I've just loaded the projects page on mobile, and that seems to be working well.
