### ISSUE TITLE
[BUG]: Projects not loading

### ISSUE THREAD

**Issue by mystichronicle** [2KAbhishek/projects#13]
### Description of the bug

For some reason Projects and other informations are not loading. Please resolve this issue.

### Steps To Reproduce

Open the website link . 

### Additional Information

<img width="935" alt="image" src="https://github.com/2KAbhishek/projects/assets/115482933/f6dba580-ae06-4d18-94f5-6efb402deb7e">

**Comment by 2KAbhishek** [comment]
The original site is functional: https://2kabhishek.github.io/projects/

If you have made modifications to the code, make sure to verify them locally before you push
