### ISSUE TITLE
[BUG]:  Merge Update Problem

### ISSUE THREAD

**Issue by Wjplatformer** [2KAbhishek/projects#3]
### Can't merge or update _account x_'s repo of `projects`
Since I'm probably the first user, I saw a problem when I changed the docs. I could not merge my commit and yours later. Is that a nooby misunderstanding of mine or a real issue? I'm not sure...

![image](https://user-images.githubusercontent.com/82447031/182602410-840c71b8-6dcf-448f-bac1-162775421c1c.png)
![image](https://user-images.githubusercontent.com/82447031/182602688-3a24379a-a48e-4d60-99ba-08cbbd023d06.png)

### Steps To Reproduce

1. Create a fork on _account x_
2. Create a PR and wait until merged by @2KAbhishek 
3. Create another PR to update this repo on _account x_
4. Can't merge!

### Additional Information

Check out https://github.com/Wjplatformer/projects/pull/1 to see the bug (or something else)

**Comment by 2KAbhishek** [comment]
I don't think it's a bug, you need to sync your branch with upstream first

**Comment by Wjplatformer** [comment]
Oh, heh. Thanks @2KAbhishek
