### ISSUE TITLE
[ENH]:  Add functionality for adding GitHub PAT via gitignore'd .env/external configuration file

### ISSUE THREAD

**Issue by jimbrig** [2KAbhishek/projects#5]
### Description

Instead of hardcoding the GitHub PAT into script.js, how can I keep my token outside of Git?

**Comment by 2KAbhishek** [comment]
You only need the PAT when you are working on it on local and have exceeded allowed requests, most simple solution would be to not commit during those lines , or not commit at all.

Once the changes are done you can push your changes and remove the PAT from GitHub.

If you are ok with introducing node dependencies then I'd suggest using dotenv.

**Comment by jimbrig** [comment]
@2KAbhishek I implemented this by deploying the static site using GitHub Actions instead of the default method and used `process.env` in `script.js` to access the secret token. If interested see the implementation in my repo here: https://github.com/jimbrig/projects.

Note the [deploy-site.yml](https://github.com/jimbrig/projects/blob/main/.github/workflows/deploy-site.yml) workflow file's usage of `env:`:

```yaml
env:
          GH_SECRET: ${{ secrets.GITHUB_TOKEN }}
```

and the [script.js added const](https://github.com/jimbrig/projects/blob/33c63e80e82737c4c7c781b463a3c26f97e71ead/script.js#L7):

```javascript
const github_token = process.env.GH_SECRET

// get information from github profile
const getProfile = async () => {
    const res = await fetch(
        `https://api.github.com/users/${username}`,
        {
            headers: {
                Accept: 'application/vnd.github+json',
                Authorization: github_token
            }
        }
    );
    const profile = await res.json();
    displayProfile(profile);
};
```

**Comment by 2KAbhishek** [comment]
Hey @jimbrig I tried opening your fork, but the live app appears empty, looks like a data fetching issue
